name: Format
description: Format code using lint and run tests

runs:
  using: 'composite'
  steps:
    - name: Lint
      run: npm run lint
      shell: bash

    - name: Test
      run: npm run test
      shell: bash
