name: E2E
description: Run e2e tests

runs:
  using: 'composite'
  steps:
    - name: Install Playwright
      run: npx playwright install
      shell: bash

    - name: Test
      run: VITE_E2E_BASE_URL=${DEPLOY_URL} npm run test:e2e
      shell: bash
