name: Deploy producation

on:
  workflow_dispatch:

jobs:
  pr-check:
    environment:
      name: 'Production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Format code
        uses: ./.github/actions/format-code

      - name: Build app
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS
        run: aws s3 sync dist s3://ofe-rmcatalog-b4465722-2ab3-457f-8dc1-a1d714619278

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E2KKC8UX5D3QXA --path "/*"
